package model;
// Generated 2026年4月14日 下午2:58:48 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Coffees generated by hbm2java
 */
@Entity
@Table(name = "coffees", catalog = "classicmodels")
public class Coffees implements java.io.Serializable {

	private String cofName;
	private Suppliers suppliers;
	private BigDecimal price;
	private int sales;
	private int total;

	public Coffees() {
	}

	public Coffees(String cofName, Suppliers suppliers, BigDecimal price, int sales, int total) {
		this.cofName = cofName;
		this.suppliers = suppliers;
		this.price = price;
		this.sales = sales;
		this.total = total;
	}

	@Id

	@Column(name = "COF_NAME", unique = true, nullable = false, length = 32)
	public String getCofName() {
		return this.cofName;
	}

	public void setCofName(String cofName) {
		this.cofName = cofName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUP_ID", nullable = false)
	public Suppliers getSuppliers() {
		return this.suppliers;
	}

	public void setSuppliers(Suppliers suppliers) {
		this.suppliers = suppliers;
	}

	@Column(name = "PRICE", nullable = false, precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "SALES", nullable = false)
	public int getSales() {
		return this.sales;
	}

	public void setSales(int sales) {
		this.sales = sales;
	}

	@Column(name = "TOTAL", nullable = false)
	public int getTotal() {
		return this.total;
	}

	public void setTotal(int total) {
		this.total = total;
	}

}
