package model;
// Generated 2026年4月14日 下午2:58:48 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Suppliers generated by hbm2java
 */
@Entity
@Table(name = "suppliers", catalog = "classicmodels")
public class Suppliers implements java.io.Serializable {

	private int supId;
	private String supName;
	private String street;
	private String city;
	private String state;
	private String zip;
	private Set<Coffees> coffeeses = new HashSet<Coffees>(0);

	public Suppliers() {
	}

	public Suppliers(int supId, String supName, String street, String city, String state) {
		this.supId = supId;
		this.supName = supName;
		this.street = street;
		this.city = city;
		this.state = state;
	}

	public Suppliers(int supId, String supName, String street, String city, String state, String zip,
			Set<Coffees> coffeeses) {
		this.supId = supId;
		this.supName = supName;
		this.street = street;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.coffeeses = coffeeses;
	}

	@Id
	@Column(name = "SUP_ID", unique = true, nullable = false)
	public int getSupId() {
		return this.supId;
	}

	public void setSupId(int supId) {
		this.supId = supId;
	}

	@Column(name = "SUP_NAME", nullable = false, length = 40)
	public String getSupName() {
		return this.supName;
	}

	public void setSupName(String supName) {
		this.supName = supName;
	}

	@Column(name = "STREET", nullable = false, length = 40)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "CITY", nullable = false, length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", nullable = false, length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZIP", length = 5)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@OneToMany(fetch = FetchType.LAZY,targetEntity=Coffees.class,
			   mappedBy = "suppliers",cascade = CascadeType.ALL)
	public Set<Coffees> getCoffeeses() {
		return this.coffeeses;
	}

	public void setCoffeeses(Set<Coffees> coffeeses) {
		this.coffeeses = coffeeses;
	}

}
