package model;
// Generated 2026年4月13日 下午1:44:24 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Coffees generated by hbm2java
 */
@Entity
@Table(name = "coffees", catalog = "classicmodels")
public class Coffees implements java.io.Serializable {

	private String cofName;
	private int supId;
	private BigDecimal price;
	private int sales;
	private int total;

	public Coffees() {
	}

	public Coffees(String cofName, int supId, BigDecimal price, int sales, int total) {
		this.cofName = cofName;
		this.supId = supId;
		this.price = price;
		this.sales = sales;
		this.total = total;
	}

	@Id

	@Column(name = "COF_NAME", unique = true, nullable = false, length = 32)
	public String getCofName() {
		return this.cofName;
	}

	public void setCofName(String cofName) {
		this.cofName = cofName;
	}

	@Column(name = "SUP_ID", nullable = false)
	public int getSupId() {
		return this.supId;
	}

	public void setSupId(int supId) {
		this.supId = supId;
	}

	@Column(name = "PRICE", nullable = false, precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "SALES", nullable = false)
	public int getSales() {
		return this.sales;
	}

	public void setSales(int sales) {
		this.sales = sales;
	}

	@Column(name = "TOTAL", nullable = false)
	public int getTotal() {
		return this.total;
	}

	public void setTotal(int total) {
		this.total = total;
	}

}
